<a href="https://colab.research.google.com/github/2025csfathimahudhac-droid/DAVLABPROGRAMS/blob/main/program2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
df=pd.read_csv("/content/Mall_Customers.csv")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [9]:
pd.read_csv("Mall_Customers.csv")

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [10]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [11]:
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [12]:
df.shape

(200, 5)

In [13]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [14]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [16]:
df.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [17]:
df["Age"].mean()

np.float64(38.85)

In [18]:
df["Age"].median()

36.0

In [19]:
df["Age"].mode()

0    32
Name: Age, dtype: int64

In [20]:
df["Age"].var()

195.13316582914584

In [21]:
df["Age"].std()

13.969007331558883

In [22]:
df["Age"].min()

18

In [23]:
df["Age"].max()

70

In [24]:
df["Age"].count()

np.int64(200)

In [25]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [26]:
df["Gender"].nunique()

2

In [27]:
df["Gender"].value_counts()

Gender
Female    112
Male       88
Name: count, dtype: int64

In [28]:
df.isnull()

     CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                   False
1         False   False  False               False                   False
2         False   False  False               False                   False
3         False   False  False               False                   False
4         False   False  False               False                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]

In [29]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [30]:
df.isnull().mean() * 100

CustomerID                0.0
Gender                    0.0
Age                       0.0
Annual Income (k$)        0.0
Spending Score (1-100)    0.0
dtype: float64

In [31]:
df.dropna()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [32]:
df.fillna(0)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [33]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Length: 200, dtype: bool

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.drop_duplicates()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [36]:
df["Age"]

0      19
1      21
2      20
3      23
4      31
       ..
195    35
196    45
197    32
198    32
199    30
Name: Age, Length: 200, dtype: int64

In [37]:
df[["Age", "Gender", "Annual Income (k$)"]]

     Age  Gender  Annual Income (k$)
0     19    Male                  15
1     21    Male                  15
2     20  Female                  16
3     23  Female                  16
4     31  Female                  17
..   ...     ...                 ...
195   35  Female                 120
196   45  Female                 126
197   32    Male                 126
198   32    Male                 137
199   30    Male                 137

[200 rows x 3 columns]

In [38]:
df.iloc[0:5]

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [39]:
df[df["Age"] > 30]

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
4             5  Female   31                  17                      40
6             7  Female   35                  18                       6
8             9    Male   64                  19                       3
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
..          ...     ...  ...                 ...                     ...
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18

[138 rows x 5 columns]

In [40]:
df.sort_values("Age")

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
33           34    Male   18                  33                      92
114         115  Female   18                  65                      48
91           92    Male   18                  59                      41
65           66    Male   18                  48                      59
68           69    Male   19                  48                      59
..          ...     ...  ...                 ...                     ...
67           68  Female   68                  48                      48
108         109    Male   68                  63                      43
57           58    Male   69                  44                      46
70           71    Male   70                  49                      55
60           61    Male   70                  46                      56

[200 rows x 5 columns]

In [41]:
df.rename(columns={"Age": "Age_Years"})

     CustomerID  Gender  Age_Years  Annual Income (k$)  Spending Score (1-100)
0             1    Male         19                  15                      39
1             2    Male         21                  15                      81
2             3  Female         20                  16                       6
3             4  Female         23                  16                      77
4             5  Female         31                  17                      40
..          ...     ...        ...                 ...                     ...
195         196  Female         35                 120                      79
196         197  Female         45                 126                      28
197         198    Male         32                 126                      74
198         199    Male         32                 137                      18
199         200    Male         30                 137                      83

[200 rows x 5 columns]

In [42]:
df["Bonus"] = df["Annual Income (k$)"] * 0.10

In [43]:
df.drop("Bonus", axis=1)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [44]:
df.groupby("Gender")

In [45]:
df.groupby("Gender")["Age"].mean()

Gender
Female    38.098214
Male      39.806818
Name: Age, dtype: float64

In [47]:
df2=df.copy()

In [48]:
pd.concat([df,df2])

,CustomerID,Gender,Age,Annual Income (k$),Spending Score (1-100),Bonus
0,1,Male,19,15,39,1.5
1,2,Male,21,15,81,1.5
2,3,Female,20,16,6,1.6
3,4,Female,23,16,77,1.6
4,5,Female,31,17,40,1.7
...,...,...,...,...,...,...
195,196,Female,35,120,79,12.0
196,197,Female,45,126,28,12.6
197,198,Male,32,126,74,12.6
198,199,Male,32,137,18,13.7
199,200,Male,30,137,83,13.7

In [49]:
pd.merge(df, df2, on="CustomerID")

,CustomerID,Gender_x,Age_x,Annual Income (k$)_x,Spending Score (1-100)_x,Bonus_x,Gender_y,Age_y,Annual Income (k$)_y,Spending Score (1-100)_y,Bonus_y
0,1,Male,19,15,39,1.5,Male,19,15,39,1.5
1,2,Male,21,15,81,1.5,Male,21,15,81,1.5
2,3,Female,20,16,6,1.6,Female,20,16,6,1.6
3,4,Female,23,16,77,1.6,Female,23,16,77,1.6
4,5,Female,31,17,40,1.7,Female,31,17,40,1.7
...,...,...,...,...,...,...,...,...,...,...,...
195,196,Female,35,120,79,12.0,Female,35,120,79,12.0
196,197,Female,45,126,28,12.6,Female,45,126,28,12.6
197,198,Male,32,126,74,12.6,Male,32,126,74,12.6
198,199,Male,32,137,18,13.7,Male,32,137,18,13.7
199,200,Male,30,137,83,13.7,Male,30,137,83,13.7